// Auto-generated by `scripts/gen-registry.ts` (DO NOT EDIT)
// Refer to `CONTRIBUTING.md` for adding a new stack

// Auto-imported stacks
import ember from "@impl/ember";
import react from "@impl/react";
import ruby from "@impl/ruby";

const StackIdArr = ["ember", "react", "ruby"] as const;
const ALL_STACKS = [ember, react, ruby] as const;

export { ALL_STACKS, StackIdArr };
